// Code generated by mockery v2.14.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Clocker is an autogenerated mock type for the Clocker type
type Clocker struct {
	mock.Mock
}

// Now provides a mock function with given fields:
func (_m *Clocker) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

type mockConstructorTestingTNewClocker interface {
	mock.TestingT
	Cleanup(func())
}

// NewClocker creates a new instance of Clocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClocker(t mockConstructorTestingTNewClocker) *Clocker {
	mock := &Clocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
